### ISSUE TITLE
[Question] about saving JSON

### ISSUE THREAD

**Issue by oleteacher** [yakovlevga/brickyeditor#1]
Great project! Really like how clean and fast things are with brickyeditor. 

"Since BrickyEditor can save blocks as JSON"

Could you explain or maybe show example how edited content is saved to JSON file(s)? I do not understand how to save the content of a modified page to a JSON file.

Thanks for sharing your project.

Susan

**Comment by yakovlevga** [comment]
Hi! You can use editor.getData() function, to retrive array of blocks, then just stringify it to JSON.
There is sample in demo page http://brickyeditor.info/examples.html (select JSON representation on top left corner).

```js
$("#editor").brickyeditor({
	onload: function(editor) {
		$("#getJson").on("click", function() {
			var data = editor.getData(); // this is array of blocks
			var json = JSON.stringify(data, null, "\t"); // just stringify it to JSON
		});
	}
});
```

Sorry for poor README at this moment, I'll try to fill it in nearest time.

**Comment by oleteacher** [comment]
Thank you for info George. I will try to get my brain in gear and figure this out. Sure it is simple but not grasping today:)

No need to apologize about readme.

Thanks again.

Susan
