### ISSUE TITLE
Add i18n option

### ISSUE THREAD

**Issue by Hrumpa** [yakovlevga/brickyeditor#21]
Consider adding internationalization capabilities for messages and errors localization.

**Comment by yakovlevga** [comment]
There are locale files inside dist/locales folder in new release. For example: https://github.com/yakovlevga/brickyeditor/blob/master/dist/locales/jquery.brickyeditor.en.js. And <script src='jquery.brickyeditor.locale.js'></script> must be added after main brickyeditor script.
What do you think about, is it ok?

**Comment by Hrumpa** [comment]
Seems OK for me. Nice feature!
