### ISSUE TITLE
working on generated HTML without loading a new template 

### ISSUE THREAD

**Issue by selimgnaoui** [yakovlevga/brickyeditor#23]
Hi , 
I want to use this plugin  without loading an external template , In fact  I just need to update/modify/delete content on my html page (generated by another script) and don't need to use nav-menu at the right side to add new content, do you have some suggestions ? 
Example Scenario : server will generate html and render it in a new page and then I want the user to have the possibilty to  just modify the content of the page ( don't need to add some new content ) , 

I've already found a solution but it doesn't  seem to be the best one  : 
generated html will be saved on  Template.html ... 

Thank you ^^

**Comment by yakovlevga** [comment]
Hi! Thanks for question =)
So, you want wysiwyg just for inline html editing?
BrickyEditor is more about templates and block and less about inline html editing.
I think Medium editor should perfect fits your needs:
http://yabwe.github.io/medium-editor/

**Comment by selimgnaoui** [comment]
Hi , 
omg ! Exactly what i'm looking for ^^ Thank you for your answer

**Comment by yakovlevga** [comment]
👍
