### ISSUE TITLE
Demo Examples not working

### ISSUE THREAD

**Issue by benoror** [yakovlevga/brickyeditor#33]
http://brickyeditor.info/examples.html is gone 😢

**Comment by yakovlevga** [comment]
Hi! Thanks for the comment. I'll fix this at nearest time.

**Comment by theodorosploumis** [comment]
Maybe use GitHub pages to do this. Thanks.

**Comment by yakovlevga** [comment]
@theodorosploumis thanx for the advice, fix it with github pages :)
