### ISSUE TITLE
Error when trying to change Link from image field

### ISSUE THREAD

**Issue by digitalManiac** [yakovlevga/brickyeditor#36]
Hi,
Before anything, I would like to congratulate you for brickyeditor. It is a very promising plugin although I'm still trying to figure out how to use it properly.
At the moment I can create elements, store them and modify them.
It works great except when trying to modify a link over an image. I get this error:
"_Uncaught (in promise) TypeError: link.getLinkPromptParams is not a function at ImageField.getPromptParams (jquery.brickyeditor.js:1135)_"
The popup when clicking on the image doesn't come out anymore once the link has been filled.
Could you please help me ?

PS: there is a tiny typo I notice on line 1144 
this.$field.css('background-image', "url(" + src +")" );
instead of 
this.$field.css('background-image', "url(" + src);

**Comment by digitalManiac** [comment]
Got it working ! I'm not sure it is the most elegant coding style but it makes the job :

**Line 1128 replace**
_new BrickyEditor.Prompt.PromptParameter('src', BrickyEditor.EditorStrings.imageFieldLinkTitle, this.data.url, BrickyEditor.EditorStrings.imageFieldLinkPlaceholder),_ 
**with**
_new BrickyEditor.Prompt.PromptParameter('src', BrickyEditor.EditorStrings.imageFieldLinkTitle, this.data.src, BrickyEditor.EditorStrings.imageFieldLinkPlaceholder),_

**Line 1133 replace**
_var link = this.data.link ? this.data.link : new BrickyEditor.HtmlLinkParams();_
**with**
_var link = this.data.link ? new BrickyEditor.HtmlLinkParams(this.data.link.href, this.data.link.title,this.data.link.target).getLinkPromptParams() : new BrickyEditor.HtmlLinkParams('','','').getLinkPromptParams()_

**Comment out line 1134**
_//var linkParams = link.getLinkPromptParams();_

**Line 1135 replace** 
_return params.concat(linkParams);_
**with**
_return params.concat(link);_ 

For more clarity, please find attached a copy of the modified version, should you incorporate it to your next release.
Hope it helps someone.
Cheers !

[jquery.brickyeditor.zip](https://github.com/yakovlevga/brickyeditor/files/3197213/jquery.brickyeditor.zip)

**Comment by yakovlevga** [comment]
Thanks for pointing this out and sorry for so late response :)
