### ISSUE TITLE
Consider new options: formSelector and inputSelector

### ISSUE THREAD

**Issue by Hrumpa** [yakovlevga/brickyeditor#8]
This can help to simplify the use of the editor inside forms. Not a big issue though.
For now it is possible to assign value to the input like this:
```javascript
ignoreHtml: true,
onload: function (editor) {
    $(formSelector).submit(function () {
        $(inputSelector).val(JSON.stringify(editor.getData()));
    });
}
```

**Comment by yakovlevga** [comment]
Thanks for idea! Will add in future releases.
